---
title: Configure Security -> Virtualization Based Security
description: Configure VBS
privilege: TrustedInstaller
actions:

  # Disabling VBS improves gaming performance
  # https://support.microsoft.com/en-us/windows/options-to-optimize-gaming-performance-in-windows-11-a255f612-2949-4373-a566-ff6f3f474613

  - !run:
    path: "%ProgramFiles%\\Revision Tool"
    exe: "revitool.exe"
    args: "tweaks security vbs disable" # automatically disables Memory Integrity (HVCI) as well
    wait: true
    runas: currentUserElevated